# pyproject.toml

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wildfire_ROS_models"
version = "0.1.0"
description = "A package for wildfire ROS model development, benchmarking and testing"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
    { name = "Jean-Baptiste Filippi", email = "filippi_j@univ-corse.fr" }
]
dependencies = [
    "matplotlib>=3.5.0",
    "numpy>=1.21.0",
    "pytest>=9.1.1",
    "salib>=1.5.2",
    "scikit-learn>=1.0.2",
    "tensorflow>=2.21.0",
]

[project.urls]
Homepage = "https://github.com/forefireAPI/wildfire_ROS_models/"
